default: &default
  adapter: postgresql
  encoding: unicode
  url: <%= ENV.fetch('DATABASE_URL', 'postgres://tour-search:tour-search@localhost:5432/tour-search') %>

development:
  <<: *default

test:
  <<: *default
  url: <%= ENV.fetch('TEST_DATABASE_URL', 'postgres://tour-search:tour-search@localhost:5432/tour-search-test') %>

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
  sslmode: require
